# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cat
  pod 'Firebase/Core'

  target 'catTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
